apiVersion: v1
kind: pod
metadata:
    name: resource
    namespace: expense
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
         requests:
            cpu: 100m
            memory: 68Mi
        limits:
            cpu: 120m
            memory: 100Mi
